
import java.awt.Color;
import java.sql.Connection;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.proteanit.sql.DbUtils;
import javax.swing.JOptionPane;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;
import javax.swing.table.TableModel;
/**
 *
 * @author sujeet
 */
public class waiteractmgmt extends javax.swing.JFrame {
String host="jdbc:mysql://localhost:3306/login";
String username="root";
String password="admin";
Statement st=null;
public void connection() throws ClassNotFoundException
{
    try
    {
        Class.forName("com.mysql.jdbc.Driver");
    }
    catch(Exception e)
    {
        System.out.println(e);
    }
}
    public void connection1()
    {
        try{
            connection();
            Connection conn=DriverManager.getConnection(host,username,password);
            st=conn.createStatement();
        }
        catch(Exception e)
    {
        JOptionPane.showMessageDialog(null, e);
    }
    }
    public void fetch_data()
    {
        try{
            
            connection1();
            String sql="select * from waiter";
            ResultSet rs=st.executeQuery(sql);
            jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        }
            catch(Exception e)
                    {
                    JOptionPane.showMessageDialog(null, e); 
                    fetch_data();
                  }
    }
    public waiteractmgmt() {
        initComponents();
        setResizable(false);
        setTitle("Waiter Account Management");
        initialize();
        setLocation(150,40);
        setSize(1067,660);
        
    }
private void initialize() {
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("final logo.PNG")));
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        eid = new javax.swing.JTextField();
        id = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        mono = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        address1 = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jLabel20 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setBackground(new java.awt.Color(255, 255, 255));
        setMinimumSize(new java.awt.Dimension(1070, 657));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Button-Add-icon.png"))); // NOI18N
        jButton1.setText("Insert");
        jButton1.setToolTipText("Insert");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 400, 110, 31);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/Trash-empty-icon (1).png"))); // NOI18N
        jButton2.setText("Delete");
        jButton2.setToolTipText("Delete");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(180, 400, 110, 31);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/system-software-update-icon.png"))); // NOI18N
        jButton3.setText("Update");
        jButton3.setToolTipText("Update");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(70, 430, 110, 31);

        jButton4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/User-New-icon.png"))); // NOI18N
        jButton4.setText("New");
        jButton4.setToolTipText("Reset all field.");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(180, 430, 110, 31);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTable2.setToolTipText("Waiter Accounts Database Table");
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 110, 680, 430);

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel12.setText("Email-ID");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(20, 240, 70, 14);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setText("Id");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(20, 160, 40, 20);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel13.setText("Mobile No");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(20, 280, 80, 14);

        eid.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        eid.setToolTipText("Enter emailID");
        getContentPane().add(eid);
        eid.setBounds(130, 230, 194, 30);

        id.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        id.setToolTipText("Enter ID here.");
        id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idActionPerformed(evt);
            }
        });
        id.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                idKeyTyped(evt);
            }
        });
        getContentPane().add(id);
        id.setBounds(130, 150, 194, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("Name");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(20, 200, 80, 14);

        name.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        name.setToolTipText("Enter name ");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(130, 190, 194, 30);

        mono.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        mono.setToolTipText("Enter Mobile no ");
        mono.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                monoKeyTyped(evt);
            }
        });
        getContentPane().add(mono);
        mono.setBounds(130, 270, 194, 30);

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Provide details below.");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(20, 110, 180, 30);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Light", 1, 24)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/users-icon (2).png"))); // NOI18N
        jLabel5.setText("Waiter Account Management");
        jLabel5.setToolTipText("Create user account and manage users.");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(36, 33, 420, 48);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("Address");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(20, 320, 70, 20);

        address1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        address1.setToolTipText("Enter Address.");
        getContentPane().add(address1);
        address1.setBounds(130, 310, 190, 30);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("close");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(940, 583, 90, 30);

        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/photos/37169943-blur-images.png"))); // NOI18N
        jLabel20.setPreferredSize(new java.awt.Dimension(800, 600));
        getContentPane().add(jLabel20);
        jLabel20.setBounds(0, 0, 1070, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
if(id.getText().isEmpty()||mono.getText().isEmpty()||
        name.getText().isEmpty()||eid.getText().isEmpty()||address1.getText().isEmpty())
{
    JOptionPane.showMessageDialog(null,"some of the field is empty. please fill all the field");
}
    else{
            
            
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           
        }
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","admin");
        } catch (SQLException ex) {
            
        }
        try{
            int p=JOptionPane.showConfirmDialog(null, "Is that right ?","Insert",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
            String sql ="Insert into waiter(WID,wname,wemailid,wmobileno,waddress)values(?,?,?,?,?)";

            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1,id.getText());
            ps.setString(2,name.getText());
            ps.setString(3,eid.getText());
           ps.setString(4,mono.getText());
            ps.setString(5,address1.getText());
            ps.execute();
            fetch_data();
            
            JOptionPane.showMessageDialog(null, "inserted successfully");
             id.setText("");
       
        mono.setText("");
        name.setText("");
        eid.setText("");
        address1.setText("");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            fetch_data();
        }
}
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           
        }
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","admin");
        } catch (SQLException ex) {
          
        }
        try{
            int p=JOptionPane.showConfirmDialog(null, "Is that right ?","Insert",JOptionPane.YES_NO_OPTION);
            if(p==0)
            {
            String sql ="delete from waiter where wid=?";

            PreparedStatement ps=conn.prepareStatement(sql);
            ps.setString(1,id.getText());

            ps.execute();
            fetch_data();
            
            JOptionPane.showMessageDialog(null, "deleted successfully");
             id.setText("");
       
        mono.setText("");
        name.setText("");
        eid.setText("");
        address1.setText("");
        }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e);
            fetch_data();
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         String a=id.getText();
         String b=name.getText();
         String c=eid.getText();
         String d=mono.getText();
         String e=address1.getText();
        
        try {
            Class.forName("com.mysql.jdbc.Driver");
        } catch (ClassNotFoundException ex) {
           
        }
        Connection conn = null;
        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/login","root","admin");
        } catch (SQLException ex) {
            Logger.getLogger(adminactmgmt.class.getName()).log(Level.SEVERE, null, ex);
        }
        try{
            int p= JOptionPane.showConfirmDialog(null, "Are you sure?","update",JOptionPane.YES_NO_OPTION);
            {
                if(p==0){
            String sql = "Update waiter set wname='"+b+"',wemailid='"+c+"',wmobileno='"+d+"',waddress='"+e+"' where wid='"+a+"'";

            PreparedStatement ps=conn.prepareStatement(sql);
           ps.execute();
            fetch_data();
            JOptionPane.showMessageDialog(null, "updated successfully");
             id.setText("");
       
        mono.setText("");
        name.setText("");
        eid.setText("");
        address1.setText("");
        }
                        fetch_data();

        }
        }
        catch(Exception ex)
        {
            JOptionPane.showMessageDialog(null,ex);
            //JOptionPane.showMessageDialog(null, "please check the number of product item. If one item code is already in the database then you can not save another record to database.");
        
        }
  fetch_data();
    
    }//GEN-LAST:event_jButton3ActionPerformed
public void close(){
 WindowEvent winClosingEvent =new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
 Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(winClosingEvent);
}
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        
        id.setText("");
        mono.setText("");
        name.setText("");
        eid.setText("");
        address1.setText("");
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        int SelectedRow =jTable2.getSelectedRow();
        DefaultTableModel model=(DefaultTableModel)jTable2.getModel();
        id.setText(model.getValueAt(SelectedRow, 0).toString());
        name.setText(model.getValueAt(SelectedRow, 1).toString());
        eid.setText(model.getValueAt(SelectedRow, 2).toString());
        mono.setText(model.getValueAt(SelectedRow, 3).toString());
        address1.setText(model.getValueAt(SelectedRow, 4).toString());
       
    }//GEN-LAST:event_jTable2MouseClicked

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        fetch_data();
    }//GEN-LAST:event_formWindowOpened

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idActionPerformed

    private void idKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idKeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_idKeyTyped

    private void monoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_monoKeyTyped
        char c=evt.getKeyChar();
        if(!Character.isDigit(c)||c==KeyEvent.VK_BACK_SPACE||c==KeyEvent.VK_DELETE)
        {
            evt.consume();
        }
    }//GEN-LAST:event_monoKeyTyped

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
      this.dispose();
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(useractmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(useractmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(useractmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(useractmgmt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new waiteractmgmt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField address1;
    private javax.swing.JTextField eid;
    private javax.swing.JTextField id;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField mono;
    private javax.swing.JTextField name;
    // End of variables declaration//GEN-END:variables
}
